[package]
name = "ferritin-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
urlencoding.workspace = true
serde_repr.workspace = true
once_cell.workspace = true
bitflags.workspace = true
serde = { workspace = true }
thiserror = { workspace = true }
