[package]
name = "ferritin-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
ferritin-pymol = { path = "../ferritin-pymol" }
pdbtbx.workspace = true
itertools.workspace = true
lazy_static = "1.5.0"
ndarray = "0.16.1"

[dev-dependencies]
ferritin-test-data = { path = "../ferritin-test-data" }
