[package]
name = "ferritin"
version.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
edition.workspace = true

[features]
default = []
mesh = ["dep:ferritin-structure-mesh"]
plms = ["dep:ferritin-plms"]
full = ["mesh", "plms", "molviewspec"]
molviewspec = ["dep:ferritin-molviewspec"]
# cellscape = ["dep:ferritin-cellscape"]
# pymol = ["dep:ferritin-pymol"]


[dependencies]
ferritin-core = { path = "../ferritin-core" }

# Optional dependencies
ferritin-structure-mesh = { path = "../ferritin-structure-mesh", optional = true }
ferritin-plms = { path = "../ferritin-plms", optional = true }
ferritin-molviewspec = { path = "../ferritin-molviewspec", optional = true }
# ferritin-cellscape = { path = "../ferritin-cellscape", optional = true }
# ferritin-pymol = { path = "../ferritin-pymol", optional = true }
