[package]
name = "ferritin"
version.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
edition.workspace = true

[features]
default = []
bevy = ["dep:ferritin-bevy"]
plms = ["dep:ferritin-plms"]
full = ["bevy", "plms", "molviewspec"]
molviewspec = ["dep:ferritin-molviewspec"]
# cellscape = ["dep:ferritin-cellscape"]
# pymol = ["dep:ferritin-pymol"]


[dependencies]
# Core is always included
ferritin-core = { path = "../ferritin-core" }

# Optional dependencies
ferritin-bevy = { path = "../ferritin-bevy", optional = true }
ferritin-plms = { path = "../ferritin-plms", optional = true }
ferritin-molviewspec = { path = "../ferritin-molviewspec", optional = true }
# ferritin-cellscape = { path = "../ferritin-cellscape", optional = true }
# ferritin-pymol = { path = "../ferritin-pymol", optional = true }
