[package]
name = "ferritin-featurizers"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
ferritin-core = { path = "../ferritin-core" }
pdbtbx.workspace = true
itertools.workspace = true
candle-core = "0.7.2"
strum = { version = "0.26", features = ["derive"] }
clap = "4.5.20"
anyhow.workspace = true


[dev-dependencies]
ferritin-test-data = { path = "../ferritin-test-data" }
assert_cmd = "2.0.16"
tempfile = "3.13.0"
