[package]
name = "ferritin-test-data"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
tempfile = "3.15.0"
