//! Tests for ProteinMPNNRunner — model loading and inference via the public API.

#[path = "support/mod.rs"]
mod support;

#[cfg(test)]
mod tests {
    use super::support::parity::{ParityFixture, assert_distribution_close};
    use candle_core::Device;
    use ferritin_plms::ProteinMPNNRunner;
    use ferritin_plms::ligandmpnn::configs::{MPNNExecConfig, ModelTypes, RunConfig};
    use ferritin_test_data::TestFile;

    const KL_THRESHOLD: f64 = 0.01;

    fn run_config() -> RunConfig {
        RunConfig {
            model_type: Some(ModelTypes::ProteinMPNN),
            seed: None,
            temperature: None,
            verbose: None,
            save_stats: None,
            batch_size: None,
            number_of_batches: None,
            file_ending: None,
            zero_indexed: None,
            homo_oligomer: None,
            fasta_seq_separation: None,
        }
    }

    #[test]
    fn test_pmpnn_runner_from_path_loads() {
        let (weights_path, _handle) = TestFile::ligmpnn_pmpnn_01()
            .create_temp()
            .expect("Failed to extract test weights");
        let runner = ProteinMPNNRunner::from_path(&weights_path, Device::Cpu);
        assert!(
            runner.is_ok(),
            "ProteinMPNNRunner::from_path should succeed with embedded test weights: {:?}",
            runner.err()
        );
    }

    #[test]
    fn test_pmpnn_runner_get_pseudo_probabilities() {
        let (weights_path, _handle) = TestFile::ligmpnn_pmpnn_01()
            .create_temp()
            .expect("Failed to extract test weights");
        let runner = ProteinMPNNRunner::from_path(&weights_path, Device::Cpu)
            .expect("Failed to load ProteinMPNNRunner");

        let (pdb_path, _pdb_handle) = TestFile::protein_02()
            .create_temp()
            .expect("Failed to extract test PDB");

        let exec_config = MPNNExecConfig::new(
            Device::Cpu,
            pdb_path,
            run_config(),
            None,
            None,
            None,
            None,
            None,
        )
        .expect("Failed to create MPNNExecConfig");

        let features = exec_config
            .generate_protein_features()
            .expect("Failed to generate protein features");

        let probs = runner
            .get_pseudo_probabilities(&features)
            .expect("get_pseudo_probabilities should succeed");

        assert!(
            !probs.is_empty(),
            "Expected non-empty pseudo-probability results"
        );
        for pp in &probs {
            assert!(pp.pseudo_prob >= 0.0 && pp.pseudo_prob <= 1.0);
        }
    }

    /// Numerical parity test: ProteinMPNN Rust vs Python reference.
    ///
    /// Requires fixture generated by `scripts/generate_proteinmpnn_fixtures.py`.
    /// Run: `cargo test test_pmpnn_parity -- --include-ignored`
    #[test]
    #[ignore = "requires fixture: run scripts/generate_proteinmpnn_fixtures.py first"]
    fn test_pmpnn_parity_vs_python_reference() {
        let device = Device::Cpu;

        // Python-reference log-probs, shape (L, 21). ProteinMPNN has no special
        // tokens, so the reference rows align 1:1 with residues.
        // Skips (loudly) while no 1BC8_log_probs fixture is committed — see
        // PARITY_COVERAGE and ferritin-100.20.
        let Some(fixture) = ParityFixture::load_or_skip("1BC8_log_probs", &device)
            .expect("ProteinMPNN parity fixture lookup failed")
        else {
            return;
        };
        let ref_log_probs = fixture.tensor("log_probs").expect("missing 'log_probs'");
        let (_, vocab_size) = ref_log_probs.dims2().expect("expected 2D tensor");
        assert_eq!(vocab_size, 21, "ProteinMPNN vocab is 21 amino acids");
        let ref_probs = ref_log_probs.exp().expect("exp failed");

        // Run Rust model on 1BC8.pdb (same structure used for fixture generation)
        let (weights_path, _weights_handle) = TestFile::ligmpnn_pmpnn_01()
            .create_temp()
            .expect("Failed to extract test weights");
        let runner = ProteinMPNNRunner::from_path(&weights_path, device.clone())
            .expect("Failed to load ProteinMPNNRunner");

        let (pdb_path, _pdb_handle) = TestFile::protein_02()
            .create_temp()
            .expect("Failed to extract 1BC8.pdb");

        let exec_config = MPNNExecConfig::new(
            device.clone(),
            pdb_path,
            run_config(),
            None,
            None,
            None,
            None,
            None,
        )
        .expect("Failed to create MPNNExecConfig");

        let features = exec_config
            .generate_protein_features()
            .expect("Failed to generate protein features");

        // get_log_probs returns (L, 21) log-probabilities
        let rust_probs = runner
            .get_log_probs(&features)
            .expect("get_log_probs failed")
            .exp()
            .expect("exp failed");

        // ProteinMPNN has no special tokens; reference and Rust rows align 1:1.
        assert_distribution_close(&rust_probs, &ref_probs, KL_THRESHOLD)
            .expect("ProteinMPNN distribution parity");
    }
}
