//! Integration smoke tests for the AMPLIFY Candle ports.

mod support;

use ferritin_plms::amplify::amplify_runner::{AmplifyModels, AmplifyRunner};
use ferritin_plms::device;
use support::model_harness::{TEST_SEQUENCE, run_remote_amplify_prediction_smoke};
use support::parity::{ParityFixture, SpecialTokens, align_rows, assert_logits_close};

/// Max absolute logit difference threshold (matching ferritin-1ti issue spec of 1e-3).
const AMPLIFY_LOGIT_TOLERANCE: f32 = 1e-3;

/// Reference sequences from the ferritin-1ti issue spec.
const PARITY_SEQUENCES: &[(&str, &str)] = &[
    ("ubiquitin_nterm", "MQIFVKTLTGK"),
    ("glycine_repeat", "GGGGGGG"),
    ("alt_charged", "KEKEKEK"),
];

fn load_amplify_120m() -> AmplifyRunner {
    AmplifyRunner::from_pretrained(AmplifyModels::AMP120M, device(false).unwrap())
        .expect("Failed to load AMPLIFY 120M model")
}

#[test]
#[ignore = "requires downloading model files"]
fn test_load_amplify_120m() {
    run_remote_amplify_prediction_smoke(AmplifyModels::AMP120M)
        .expect("Failed to load AMPLIFY 120M model");
}

#[test]
#[ignore = "requires downloading model files"]
fn test_amplify_120m_prediction() {
    run_remote_amplify_prediction_smoke(AmplifyModels::AMP120M)
        .expect("Failed to get prediction from AMPLIFY 120M");
}

#[test]
#[ignore = "requires downloading model files"]
fn test_amplify_120m_probabilities() {
    let amplify = load_amplify_120m();
    let probabilities = amplify.get_pseudo_probabilities(TEST_SEQUENCE);
    assert!(
        probabilities.is_ok(),
        "Failed to get pseudo-probabilities: {:?}",
        probabilities.err()
    );
    let probabilities = probabilities.unwrap();
    assert!(
        !probabilities.is_empty(),
        "Probabilities should not be empty"
    );

    let unique_positions: std::collections::HashSet<_> =
        probabilities.iter().map(|p| p.position).collect();
    assert_eq!(
        unique_positions.len(),
        TEST_SEQUENCE.len(),
        "Should have predictions for each position in the sequence"
    );
}

#[test]
#[ignore = "requires downloading model files"]
fn test_amplify_120m_contact_map() {
    let amplify = load_amplify_120m();
    let contact_map = amplify.get_contact_map(TEST_SEQUENCE);
    assert!(
        contact_map.is_ok(),
        "Failed to get contact map: {:?}",
        contact_map.err()
    );

    let contacts = contact_map.unwrap();
    assert!(!contacts.is_empty(), "Contact map should not be empty");

    let sequence_len = TEST_SEQUENCE.len();
    for contact in &contacts {
        assert!(
            contact.position_1 < sequence_len,
            "Position 1 should be valid"
        );
        assert!(
            contact.position_2 < sequence_len,
            "Position 2 should be valid"
        );
        assert!(
            !contact.contact_estimate.is_nan(),
            "Contact estimate should be a valid number"
        );
    }

    // Regression for ferritin-100.3: labels must be the actual residues, not
    // '?' (the old code decoded the position index as a token id, so every
    // position >= vocab size, i.e. essentially all of this ~250-residue
    // protein, came back '?').
    let seq: Vec<char> = TEST_SEQUENCE.chars().collect();
    for contact in &contacts {
        assert_eq!(
            contact.amino_acid_1, seq[contact.position_1],
            "amino_acid_1 at position {} should be the input residue",
            contact.position_1
        );
        assert_eq!(
            contact.amino_acid_2, seq[contact.position_2],
            "amino_acid_2 at position {} should be the input residue",
            contact.position_2
        );
    }
}

/// Numerical parity: AMPLIFY Rust logits vs HuggingFace Python reference.
///
/// Requires:
///   1. AMPLIFY AMP120M weights downloaded (cached by HF hub)
///   2. Fixture at `tests/fixtures/amplify_parity.safetensors`
///      generated by `scripts/generate_amplify_fixtures.py`
///
/// The fixture is committed, so this runs in a plain `cargo test` once the
/// weights are cached; gated on `FERRITIN_HF_TESTS=1` so the PR path skips the
/// download. See `support::parity::hf_tests_enabled`.
///
/// Run: `FERRITIN_HF_TESTS=1 cargo test -p ferritin-plms test_amplify_parity`
#[test]
fn test_amplify_parity_vs_python_reference() {
    if !support::parity::hf_tests_enabled() {
        eprintln!(
            "skipping AMPLIFY parity: set FERRITIN_HF_TESTS=1 to run (downloads AMPLIFY_120M weights)"
        );
        return;
    }

    let amplify = load_amplify_120m();
    let device = amplify
        .run_forward(PARITY_SEQUENCES[0].1)
        .expect("forward pass failed")
        .logits
        .device()
        .clone();

    // The AMPLIFY reference (generate_amplify_fixtures.py) strips BOS/EOS and
    // stores only the L interior residue rows, so align the Rust output.
    let fixture = ParityFixture::load("amplify_parity", &device)
        .expect("failed to load AMPLIFY parity fixture");

    for (name, sequence) in PARITY_SEQUENCES {
        let ref_logits = fixture
            .tensor(&format!("{name}_logits"))
            .expect("fixture missing logits key");

        let output = amplify.run_forward(sequence).expect("forward pass failed");
        let rust_logits = align_rows(&output.logits, SpecialTokens::BOS_EOS).expect("align failed");
        assert_logits_close(&rust_logits, ref_logits, AMPLIFY_LOGIT_TOLERANCE)
            .unwrap_or_else(|e| panic!("{name}: {e}"));
        println!("{name}: logit parity OK (tol {AMPLIFY_LOGIT_TOLERANCE:.1e})");
    }
}
