//! Integration smoke tests for the ESM2 Candle ports.

// cargo test test_load_esm2_8m --features metal -- --ignored
// cargo test test_esm2_150m_embedding --features metal -- --ignored

mod support;

use anyhow::Result;
use ferritin_plms::ESM2Models;
use support::model_harness::run_remote_esm2_smoke;

/// Max absolute logit difference threshold (ferritin-lgr issue spec: 1e-3).
const ESM2_LOGIT_TOLERANCE: f32 = 1e-3;

/// Reference sequences from the ferritin-lgr issue spec (esm2_t6_8M model).
const PARITY_SEQUENCES: &[(&str, &str)] = &[
    ("ubiquitin_nterm", "MQIFVKTLTGK"),
    ("glycine_repeat", "GGGGGGGGG"),
    ("alt_charged", "KEKEKEKEK"),
    ("masked_seq", "MQ<mask>FVKTLTGK"),
];

/// Test that we can successfully load the ESM2 650M model
#[test]
#[ignore = "requires downloading model files"]
fn test_load_esm2_8m() -> Result<()> {
    run_remote_esm2_smoke(ESM2Models::T6_8M)
}

/// Test a simple embedding generation using ESM2
#[test]
#[ignore = "requires downloading model files"]
fn test_esm2_150m_embedding() -> Result<()> {
    run_remote_esm2_smoke(ESM2Models::T30_150M)
}

/// Numerical parity: ESM-2 (T6_8M) Rust logits vs HuggingFace Python reference.
///
/// Requires:
///   1. ESM2 T6_8M weights downloaded (cached by HF hub on first run)
///   2. Fixture at `tests/fixtures/esm2_parity.safetensors`
///      generated by `scripts/generate_esm2_fixtures.py`
///
/// Run: `cargo test test_esm2_parity -- --include-ignored`
#[test]
#[ignore = "requires HF model download and fixture: run scripts/generate_esm2_fixtures.py"]
fn test_esm2_parity_vs_python_reference() -> Result<()> {
    use ferritin_plms::ESM2Runner;
    use ferritin_plms::device;
    use support::parity::{ParityFixture, SpecialTokens, align_rows, assert_logits_close};

    let dev = device(false)?;
    let esm2 = ESM2Runner::load_model(ESM2Models::T6_8M, dev.clone())?;

    // The ESM2 reference (generate_esm2_fixtures.py) strips BOS/EOS and stores
    // only the L interior residue rows, so align the Rust output to match.
    let fixture = ParityFixture::load("esm2_parity", &dev)?;

    for (name, sequence) in PARITY_SEQUENCES {
        let ref_logits = fixture.tensor(&format!("{name}_logits"))?;
        let output = esm2.run_forward(sequence)?;
        let rust_logits = align_rows(&output.logits, SpecialTokens::BOS_EOS)?;
        assert_logits_close(&rust_logits, ref_logits, ESM2_LOGIT_TOLERANCE)?;
        println!("{name}: logit parity OK (tol {ESM2_LOGIT_TOLERANCE:.1e})");
    }
    Ok(())
}
