//! Integration smoke tests for the AMPLIFY Candle ports.

mod support;

use ferritin_plms::amplify::amplify_runner::{AmplifyModels, AmplifyRunner};
use ferritin_plms::device;
use support::model_harness::{TEST_SEQUENCE, run_remote_amplify_prediction_smoke};

/// Fixture produced by `scripts/generate_amplify_fixtures.py` (gitignored, not committed).
/// Generate with: `python scripts/generate_amplify_fixtures.py --output crates/ferritin-plms/tests/fixtures/`
const AMPLIFY_PARITY_FIXTURE: &str = "tests/fixtures/amplify_parity.safetensors";

/// Max absolute logit difference threshold (matching ferritin-1ti issue spec of 1e-3).
const AMPLIFY_LOGIT_TOLERANCE: f32 = 1e-3;

/// Reference sequences from the ferritin-1ti issue spec.
const PARITY_SEQUENCES: &[(&str, &str)] = &[
    ("ubiquitin_nterm", "MQIFVKTLTGK"),
    ("glycine_repeat", "GGGGGGG"),
    ("alt_charged", "KEKEKEK"),
];

fn load_amplify_120m() -> AmplifyRunner {
    AmplifyRunner::load_model(AmplifyModels::AMP120M, device(false).unwrap())
        .expect("Failed to load AMPLIFY 120M model")
}

#[test]
#[ignore = "requires downloading model files"]
fn test_load_amplify_120m() {
    run_remote_amplify_prediction_smoke(AmplifyModels::AMP120M)
        .expect("Failed to load AMPLIFY 120M model");
}

#[test]
#[ignore = "requires downloading model files"]
fn test_amplify_120m_prediction() {
    run_remote_amplify_prediction_smoke(AmplifyModels::AMP120M)
        .expect("Failed to get prediction from AMPLIFY 120M");
}

#[test]
#[ignore = "requires downloading model files"]
fn test_amplify_120m_probabilities() {
    let amplify = load_amplify_120m();
    let probabilities = amplify.get_pseudo_probabilities(TEST_SEQUENCE);
    assert!(
        probabilities.is_ok(),
        "Failed to get pseudo-probabilities: {:?}",
        probabilities.err()
    );
    let probabilities = probabilities.unwrap();
    assert!(
        !probabilities.is_empty(),
        "Probabilities should not be empty"
    );

    let unique_positions: std::collections::HashSet<_> =
        probabilities.iter().map(|p| p.position).collect();
    assert_eq!(
        unique_positions.len(),
        TEST_SEQUENCE.len(),
        "Should have predictions for each position in the sequence"
    );
}

#[test]
#[ignore = "requires downloading model files"]
fn test_amplify_120m_contact_map() {
    let amplify = load_amplify_120m();
    let contact_map = amplify.get_contact_map(TEST_SEQUENCE);
    assert!(
        contact_map.is_ok(),
        "Failed to get contact map: {:?}",
        contact_map.err()
    );

    let contacts = contact_map.unwrap();
    assert!(!contacts.is_empty(), "Contact map should not be empty");

    let sequence_len = TEST_SEQUENCE.len();
    for contact in &contacts {
        assert!(
            contact.position_1 < sequence_len,
            "Position 1 should be valid"
        );
        assert!(
            contact.position_2 < sequence_len,
            "Position 2 should be valid"
        );
        assert!(
            !contact.contact_estimate.is_nan(),
            "Contact estimate should be a valid number"
        );
    }
}

/// Numerical parity: AMPLIFY Rust logits vs HuggingFace Python reference.
///
/// Requires:
///   1. AMPLIFY AMP120M weights downloaded (cached by HF hub)
///   2. Fixture at `tests/fixtures/amplify_parity.safetensors`
///      generated by `scripts/generate_amplify_fixtures.py`
///
/// Run: `cargo test test_amplify_parity -- --include-ignored`
#[test]
#[ignore = "requires HF model download and fixture: run scripts/generate_amplify_fixtures.py"]
fn test_amplify_parity_vs_python_reference() {
    use candle_core::safetensors;
    use std::collections::HashMap;

    let fixture_path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join(AMPLIFY_PARITY_FIXTURE);
    assert!(
        fixture_path.exists(),
        "Fixture not found at {fixture_path:?}. Run scripts/generate_amplify_fixtures.py first."
    );

    let amplify = load_amplify_120m();
    let device = amplify.run_forward(PARITY_SEQUENCES[0].1)
        .expect("forward pass failed")
        .logits
        .device()
        .clone();

    let fixtures: HashMap<String, candle_core::Tensor> =
        safetensors::load(&fixture_path, &device)
            .expect("Failed to load AMPLIFY parity fixture");

    for (name, sequence) in PARITY_SEQUENCES {
        let key = format!("{name}_logits");
        let ref_logits = fixtures.get(&key)
            .unwrap_or_else(|| panic!("fixture missing key '{key}'"));

        let output = amplify.run_forward(sequence).expect("forward pass failed");
        let seq_len = sequence.len();
        // Strip BOS/EOS tokens from Rust output: indices [1..=seq_len]
        let rust_logits = output.logits
            .narrow(1, 1, seq_len)
            .expect("narrow failed")
            .squeeze(0)
            .expect("squeeze failed");

        let (rust_l, rust_v) = rust_logits.dims2().expect("dims2 failed");
        let (ref_l, ref_v) = ref_logits.dims2().expect("ref dims2 failed");
        assert_eq!(rust_l, ref_l, "{name}: sequence length mismatch");
        assert_eq!(rust_v, ref_v, "{name}: vocab size mismatch");

        let rust_flat: Vec<f32> = rust_logits.flatten_all().expect("flatten").to_vec1().expect("to_vec1");
        let ref_flat: Vec<f32> = ref_logits.flatten_all().expect("flatten").to_vec1().expect("to_vec1");

        let max_diff = rust_flat.iter()
            .zip(ref_flat.iter())
            .map(|(&r, &p)| (r - p).abs())
            .fold(0.0_f32, f32::max);

        assert!(
            max_diff <= AMPLIFY_LOGIT_TOLERANCE,
            "{name}: max absolute logit diff {max_diff:.6} exceeds tolerance {AMPLIFY_LOGIT_TOLERANCE}"
        );
        println!("{name}: max logit diff = {max_diff:.6e}");
    }
}
