//! Integration smoke tests for the ESM2 Candle ports.

// cargo test test_load_esm2_8m --features metal -- --ignored
// cargo test test_esm2_150m_embedding --features metal -- --ignored

mod support;

use anyhow::Result;
use ferritin_plms::ESM2Models;
use support::model_harness::run_remote_esm2_smoke;

/// Max absolute logit difference threshold (ferritin-lgr issue spec: 1e-3).
const ESM2_LOGIT_TOLERANCE: f32 = 1e-3;

/// Reference sequences from the ferritin-lgr issue spec (esm2_t6_8M model).
const PARITY_SEQUENCES: &[(&str, &str)] = &[
    ("ubiquitin_nterm", "MQIFVKTLTGK"),
    ("glycine_repeat", "GGGGGGGGG"),
    ("alt_charged", "KEKEKEKEK"),
    ("masked_seq", "MQ<mask>FVKTLTGK"),
];

/// Test that we can successfully load the ESM2 650M model
#[test]
#[ignore = "requires downloading model files"]
fn test_load_esm2_8m() -> Result<()> {
    run_remote_esm2_smoke(ESM2Models::T6_8M)
}

/// Test a simple embedding generation using ESM2
#[test]
#[ignore = "requires downloading model files"]
fn test_esm2_150m_embedding() -> Result<()> {
    run_remote_esm2_smoke(ESM2Models::T30_150M)
}

/// Numerical parity: ESM-2 (T6_8M) Rust logits vs HuggingFace Python reference.
///
/// Requires:
///   1. ESM2 T6_8M weights downloaded (cached by HF hub on first run)
///   2. Fixture at `tests/fixtures/esm2_parity.safetensors`
///      generated by `scripts/generate_esm2_fixtures.py`
///
/// The fixture is committed, so this runs in a plain `cargo test` once the
/// weights are cached; gated on `FERRITIN_HF_TESTS=1` so the PR path skips the
/// download. See `support::parity::hf_tests_enabled`.
///
/// Run: `FERRITIN_HF_TESTS=1 cargo test -p ferritin-plms test_esm2_parity`
#[test]
fn test_esm2_parity_vs_python_reference() -> Result<()> {
    use ferritin_plms::ESM2Runner;
    use ferritin_plms::device;
    use support::parity::{
        ParityFixture, SpecialTokens, align_rows, assert_logits_close, hf_tests_enabled,
    };

    if !hf_tests_enabled() {
        eprintln!(
            "skipping ESM2 parity: set FERRITIN_HF_TESTS=1 to run (downloads esm2_t6_8M weights)"
        );
        return Ok(());
    }

    let dev = device(false)?;
    let esm2 = ESM2Runner::from_pretrained(ESM2Models::T6_8M, dev.clone())?;

    // The ESM2 reference (generate_esm2_fixtures.py) strips BOS/EOS and stores
    // only the L interior residue rows, so align the Rust output to match.
    let fixture = ParityFixture::load("esm2_parity", &dev)?;

    for (name, sequence) in PARITY_SEQUENCES {
        let ref_logits = fixture.tensor(&format!("{name}_logits"))?;
        let output = esm2.run_forward(sequence)?;
        let rust_logits = align_rows(&output.logits, SpecialTokens::BOS_EOS)?;
        assert_logits_close(&rust_logits, ref_logits, ESM2_LOGIT_TOLERANCE)?;
        println!("{name}: logit parity OK (tol {ESM2_LOGIT_TOLERANCE:.1e})");
    }
    Ok(())
}

/// Max absolute logit difference for SaProt-35M.
///
/// Same floor as stock ESM-2: the backbone is identical, so a looser tolerance
/// here would be hiding a tokenizer or embedding-table problem rather than
/// accommodating a genuinely harder numerical path.
const SAPROT_LOGIT_TOLERANCE: f32 = 1e-3;

/// SaProt's reference sequences, as `(residue, 3Di state)` pairs.
///
/// Must stay in sync with `SAPROT_SEQUENCES` in
/// `scripts/generate_esm2_fixtures.py`. The 3Di halves are ProstT5's real
/// output for these sequences (see `test_saprot_bridge.rs`), so every pair is
/// one SaProt's 446-token vocabulary actually contains.
const SAPROT_PARITY_SEQUENCES: &[(&str, &str)] = &[
    ("ubiquitin_nterm", "MdQvIvFvVvKcTvLvTvGvKd"),
    ("glycine_repeat", "GdGdGdGdGdGdGdGdGd"),
    ("alt_charged", "KvEvKvEvKvEvKvEvKv"),
];

/// Numerical parity: SaProt-35M Rust logits vs the HuggingFace reference.
///
/// SaProt carries `Family::Esm2` and runs on the same `EsmForMaskedLM`
/// backbone as `esm2-t6-8m`, which is why it had inherited that row's parity
/// coverage by association. That inheritance covered the wrong half. What
/// differs is the alphabet: SaProt reads **two** characters per residue over a
/// 446-token (amino acid, 3Di) product vocabulary loaded from a bare
/// `vocab.txt`, against stock ESM-2's one character over 33 tokens from a
/// `tokenizer.json`. Those are different code paths in `SequenceTokenizer`, and
/// nothing was checking the SaProt one numerically (ferritin-100.34).
///
/// The failure this actually guards against is quiet: reading the pair
/// alphabet one character at a time still produces a well-formed tensor, just
/// with twice the rows and every other one `<unk>`. Comparing full logit rows
/// against the reference catches that; a shape assertion would not.
///
/// Requires:
///   1. SaProt_35M_AF2 weights (cached by HF hub on first run)
///   2. Fixture at `tests/fixtures/saprot_parity.safetensors`
///      from `python scripts/generate_esm2_fixtures.py --variant saprot`
///
/// Run: `FERRITIN_HF_TESTS=1 cargo test -p ferritin-plms test_saprot_parity`
#[test]
fn test_saprot_parity_vs_python_reference() -> Result<()> {
    use ferritin_plms::ESM2Runner;
    use ferritin_plms::device;
    use support::parity::{
        ParityFixture, SpecialTokens, align_rows, assert_logits_close, hf_tests_enabled,
    };

    if !hf_tests_enabled() {
        eprintln!(
            "skipping SaProt parity: set FERRITIN_HF_TESTS=1 to run \
             (downloads SaProt_35M_AF2 weights)"
        );
        return Ok(());
    }

    let dev = device(false)?;
    let saprot = ESM2Runner::from_pretrained(ESM2Models::SaProt35M, dev.clone())?;

    // The generator strips BOS/EOS and stores only the L residue rows, where L
    // is the RESIDUE count, not the character count.
    //
    // Named explicitly because this fixture comes from the *esm2* generator
    // under `--variant saprot`; the default inference would suggest a
    // `generate_saprot_fixtures.py` that does not exist.
    let fixture =
        ParityFixture::load_with_generator_args("saprot_parity", "esm2", "--variant saprot", &dev)?;

    for (name, sequence) in SAPROT_PARITY_SEQUENCES {
        let ref_logits = fixture.tensor(&format!("{name}_logits"))?;
        let output = saprot.run_forward(sequence)?;
        let rust_logits = align_rows(&output.logits, SpecialTokens::BOS_EOS)?;

        // Pin the residue count explicitly. If the pair alphabet were ever read
        // one character at a time this would be 2L and the row-wise comparison
        // below would fail with a confusing shape error instead of a clear one.
        assert_eq!(
            rust_logits.dim(0)?,
            sequence.len() / 2,
            "{name}: SaProt reads two characters per residue"
        );

        assert_logits_close(&rust_logits, ref_logits, SAPROT_LOGIT_TOLERANCE)?;
        println!("{name}: SaProt logit parity OK (tol {SAPROT_LOGIT_TOLERANCE:.1e})");
    }
    Ok(())
}

/// Numerical parity for the non-stock `Family::Esm2` rows: PepMLM, DPLM and
/// FastESM2.
///
/// Each of these shares the `Esm2` family tag and is run through
/// `ESM2Config::t33_650m()`, so each inherited `esm2-t6-8m`'s parity coverage by
/// association. Unlike SaProt the alphabet really is shared — all three use the
/// stock 33-token vocabulary — so what is being checked here is the other
/// assumption: that the 650M ESM-2 config is the right config for these
/// checkpoints at all. DPLM in particular is a *diffusion* model rather than a
/// masked LM, so "same backbone, different weights" is a claim worth testing
/// rather than asserting.
///
/// One honest caveat on FastESM2: its checkpoint declares `model_type:
/// fast_esm`, and the reference generator coerces it into `EsmForMaskedLM`
/// (transformers warns about this, and about a freshly-initialised
/// `contact_head` that the logits do not depend on). So this test establishes
/// that ferritin agrees with *that coercion*, which is the same coercion
/// ferritin itself performs. It does not independently establish that the
/// coercion matches Synthyra's intended semantics.
///
/// Requires the respective weights (~2.6 GB each, cached by HF hub) and the
/// fixtures from `python scripts/generate_esm2_fixtures.py --variant <name>`.
///
/// Run: `FERRITIN_HF_TESTS=1 cargo test -p ferritin-plms test_esm2_sibling_parity`
#[test]
fn test_esm2_sibling_parity_vs_python_reference() -> Result<()> {
    use ferritin_plms::ESM2Runner;
    use ferritin_plms::device;
    use support::parity::{
        ParityFixture, SpecialTokens, align_rows, assert_logits_close, hf_tests_enabled,
    };

    if !hf_tests_enabled() {
        eprintln!(
            "skipping ESM2 sibling parity: set FERRITIN_HF_TESTS=1 to run \
             (downloads PepMLM, DPLM and FastESM2 weights, ~2.6 GB each)"
        );
        return Ok(());
    }

    let dev = device(false)?;

    // Taken by value rather than iterated from a const table: none of the
    // `*Models` enums in this crate derive `Copy`, and widening a public enum
    // for a test's convenience is not this issue's business.
    let check = |model: ESM2Models, fixture_name: &str, variant: &str| -> Result<()> {
        let runner = ESM2Runner::from_pretrained(model, dev.clone())?;
        let args = format!("--variant {variant}");
        let fixture = ParityFixture::load_with_generator_args(fixture_name, "esm2", &args, &dev)?;

        for (name, sequence) in PARITY_SEQUENCES {
            // The sibling generators skip the masked sequence: these
            // checkpoints need not agree with stock ESM-2 about <mask>.
            if *name == "masked_seq" {
                continue;
            }
            let ref_logits = fixture.tensor(&format!("{name}_logits"))?;
            let output = runner.run_forward(sequence)?;
            let rust_logits = align_rows(&output.logits, SpecialTokens::BOS_EOS)?;
            assert_logits_close(&rust_logits, ref_logits, ESM2_LOGIT_TOLERANCE)?;
            println!("{variant}/{name}: logit parity OK (tol {ESM2_LOGIT_TOLERANCE:.1e})");
        }
        Ok(())
    };

    check(ESM2Models::PepMlm650M, "pepmlm_parity", "pepmlm")?;
    check(ESM2Models::Dplm650M, "dplm_parity", "dplm")?;
    check(ESM2Models::FastEsm2_650, "fastesm2_parity", "fastesm2")?;
    Ok(())
}
