[workspace]
members = [
    "ferritin-bevy",
    "ferritin-cellscape",
    "ferritin-core",
    "ferritin-esm",
    "ferritin-amplify",
    "ferritin-ligandmpnn",
    "ferritin-molviewspec",
    "ferritin-pymol",
    "ferritin-test-data",
    "ferritin-wasm-examples/*",
]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0"
bitflags = "2.6.0"
candle-core = { git = "https://github.com/huggingface/candle.git", package = "candle-core", features = [
] }
candle-examples = { git = "https://github.com/huggingface/candle.git", package = "candle-examples" }
candle-hf-hub = "0.3.3"
candle-nn = { git = "https://github.com/huggingface/candle.git", package = "candle-nn" }
candle-transformers = { git = "https://github.com/huggingface/candle.git", package = "candle-transformers" }
itertools = "0.13.0"
once_cell = "1.20.2"
pdbtbx = "0.12.0"
rand = "0.8.5"
safetensors = "0.4.5"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11.15"
serde_json = "1.0.133"
serde_repr = "0.1.19"
tokenizers = "0.21.0"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Zach Charlop-Powers<zach.charlop.powers@gmail.com>"]
description = "Molecular visualization tools"
license = "MIT OR Apache-2.0"
