[package]
name = "ferritin"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
lazy_static = "1.5.0"
pdbtbx = "0.12.0"
pseutils = { git = "https://github.com/zachcp/pseutils" }
serde = "1.0"
serde_json = "1.0.132"

[dev-dependencies]
rmp-serde = "1.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11.15"
serde_json = "1.0.132"
thiserror = "1.0.65"
