[workspace]
members = ["ferritin-core", "ferritin-pymol", "ferritin-bevy"]

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
anyhow = "1.0"
itertools = "0.13.0"
pdbtbx = "0.12.0"
serde_json = "1.0.132"
serde_bytes = "0.11.15"


[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Zach Charlop-Powers<zach.charlop.powers@gmail.com>"]
description = "Molecular visualization tools"
license = "MIT OR Apache-2.0"
