[workspace]
members = ["ferritin-core", "ferritin-pymol", "ferritin-bevy"]
resolver = "2"


[workspace.dependencies]
# Core dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.132"
serde_bytes = "0.11.15"
serde_repr = "0.1.19"
serde-pickle = "1.1"

# Utility dependencies
thiserror = "1.0"
anyhow = "1.0"
itertools = "0.13.0"
urlencoding = "2.1.3"
once_cell = "1.20.2"
bitflags = "2.6.0"
chrono = "0.4.38"


# External tools
pdbtbx = "0.12.0"
bevy = "0.14.2"
bon = "2.3.0"
glam = "0.29.0"
clap = { version = "4.5.20", features = ["derive"] }
validator = { version = "0.18", features = ["derive"] }


[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Zach Charlop-Powers<zach.charlop.powers@gmail.com>"]
description = "Molecular visualization tools"
license = "MIT OR Apache-2.0"
