[package]
name = "ferritin-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true

[features]
default = []
intern = []

[dependencies]
anyhow.workspace = true
itertools.workspace = true
strum.workspace = true

[dev-dependencies]
ferritin-test-data = { path = "../ferritin-test-data" }
