[package]
name = "ferritin-io"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
memchr.workspace = true
anyhow.workspace = true

[dev-dependencies]
ferritin-test-data = { path = "../ferritin-test-data" }
