[package]
name = "ferritin-pymol"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
ferritin-core = { path = "../ferritin-core" }
ferritin-molviewspec = { path = "../ferritin-molviewspec" }
clap.workspace = true
pdbtbx = "0.12.0"
serde = { workspace = true }
serde_json = { workspace = true }
bitflags = { workspace = true }
itertools.workspace = true
memchr = "2.7.4"
serde-pickle = "1.2"
serde_bytes = "0.11.17"
# serde_repr = "0.1.20"

[dev-dependencies]
ferritin-test-data = { path = "../ferritin-test-data" }
