[package]
name = "ferritin-cellscape"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
ferritin-core = { path = "../ferritin-core" }
pdbtbx = { workspace = true }
geo = "0.29.1"
svg = "0.18.0"
