[package]
name = "esm3-candle"
version = "0.1.0"
edition = "2021"

[dependencies]
candle-core = { workspace = true }
candle-nn = { workspace = true }
ferritin-amplify = { path = "../../ferritin-amplify" }
gloo = "0.11.0"
js-sys = "0.3.74"
wasm-bindgen = "0.2.97"
