project:
  type: website
  resources:
    - "examples/**"
    - "doc/**"

website:
  title: "ferritin"
  navbar:
    logo: ferritin.png
    left:
      - href: index.qmd
        text: home
      # - href: examples.qmd
      #   text: examples
      - text: ferritin-rustdoc
        href: doc/ferritin_core/index.html
      - text: blog
        href: posts/

    right:
      - icon: github
        href: https://github.com/zachcp/ferritin
        aria-label: GitHub

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
