project:
  type: website
  resources:
    - "examples/**"
    - "doc/**"

website:
  title: "ferritin"
  navbar:
    logo: ferritin.png
    left:
      - href: doc/ferritin_core/index.html
        text: ferritin-rustdoc
      - text: blog
        href: posts/
      - text: Related Projects
        menu:
          - text: Fennec
            href: https://github.com/ferritin-bio/fennec
          - text: Protein Language Models
            href: https://github.com/ferritin-bio/protein-language-models

    right:
      - icon: github
        href: https://github.com/ferritin-bio/ferritin
        aria-label: GitHub

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
