pub const MAX_TOPK_SEQUENCE: u32 = 32;
pub const MAX_TOPK_STRUCTURE: u32 = MAX_TOPK_SEQUENCE;
pub const MAX_TOPK_SECONDARY_STRUCTURE: u32 = MAX_TOPK_SEQUENCE;
pub const MAX_TOPK_SASA: u32 = MAX_TOPK_SEQUENCE;
pub const MAX_TOPK_FUNCTION: u32 = MAX_TOPK_SEQUENCE;
