[package]
name = "ferritin-pymol"
version = "0.1.0"
edition = "2021"

[dependencies]
ferritin-core = { path = "../ferritin-core" }
clap = { version = "4.5.20", features = ["derive"] }
serde-pickle = "1.1"
serde_bytes = "0.11.15"
chrono = "0.4.38"
validator = { version = "0.18", features = ["derive"] }
urlencoding = "2.1.3"
serde_repr = "0.1.19"
once_cell = "1.20.2"
bitflags = "2.6.0"
